export const TESTIMONIALS = [
    {
        id: 1,
        name: "JD Kubitschek",
        position: "COO",
        company: "Berkshire Construction Co.",
        // image: "/images/testimonials/john-doe.jpg",
        company_logo: "/images/BerkshireLogo.png",
        text: "We love Toolsey for its simplicity...",
        width: 175,
    },
    {
        id: 2,
        name: "Stephanie Myrick",
        position: "Office Manager",
        company: "VE Roofing",
        // image: "/images/testimonials/john-doe.jpg",
        company_logo: "/images/VeLogo.png",
        text: "all day long...literally all day long we are in and out of this tool...",
        width: 48,
    },
    {
        id: 3,
        name: "Brian Smith",
        position: "Owner",
        company: "Beardman Building Services",
        // image: "/images/testimonials/john-doe.jpg",
        company_logo: "/images/BeardLogo.png",
        text: "with Toolsey, you can just whittle it down, and not clunk up your CRM...",
        width: 64,
    },
    {
        id: 4,
        name: "Gary Barker",
        position: "Owner",
        company: "Barker Roofing",
        image: "/images/BarkerMan.png",
        company_logo: "/images/BarkerLogo.png",
        text: "Doesn’t get any better than this! Love the connection and the Toolsey staff is simply amazing!",
        width: 145,
    },
    {
        id: 5,
        name: "Aric DeGroot",
        position: "Salesperson",
        company: "Republic Roofing",
        image: "/images/RepublicMan.png",
        company_logo: "/images/RepublicLogo.png",
        text: "Toolsey allows me to do that all right at my fingertips",
        width: 205,
    },
    {
        id: 6,
        name: "Casey Mullins",
        position: "Co-Owner",
        company: "Senter Roofing",
        image: "/images/SenterMan.png",
        company_logo: "/images/SenterLogo.png",
        text: "Gone are the days of using sticky notes and invoices to take notes...",
        width: 239,
    },
];